apiVersion: v1
kind: Secret
metadata:
 name: mirror-postgres-credentials-admin
 namespace: monitoring-ns
 annotations:
   reflector.v1.k8s.emberstack.com/reflects: "database-ns/postgres-credentials-admin"
type: kubernetes.io/basic-auth
data:
  username: ""
  password: ""