apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-local-disk
  namespace: default
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate