# Secret for postgres db password (admin user)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials-admin
  namespace: database-ns
  annotations:
   reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
   reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "monitoring-ns"
type: kubernetes.io/basic-auth
stringData:
  # The pw and user will be injected by GitHub Actions when testing
  username: "admin"
  password: "${POSTGRES_PASS}"