apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-api
  namespace: nginx-gateway
spec:
  gatewayClassName: nginx
  listeners:
  - name: monitoring-dashboard-listener
    port: 80
    protocol: HTTP
    allowedRoutes:
        namespaces:
          from: All

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: monitor-frontend-route
  namespace: nginx-gateway
spec:
  parentRefs:
  - name: gateway-api
    sectionName: monitoring-dashboard-listener
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: monitoring-service
      port: 8000
      namespace: monitoring-ns