apiVersion: v1
kind: Secret
metadata:
  name: ngrok-operator-credentials
  namespace: ngrok-operator
stringData:
  # The pw and user will be injected by GitHub Actions when testing
  AUTHTOKEN: ${NGROK_AUTHTOKEN}
  API_KEY: ${NGROK_API_KEY}